In [ ]:
import pandas as pd

In [ ]:
! pip3 install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
restaurant_data= {
    'tableno': [1, 2, 3, 4, 5],
    'waitername': ['John', 'Alice', 'Bob', 'Eve', 'Charlie'],
    'order': ['Pizza', 'Burger', 'Pasta', 'Salad', 'Sushi'],
    'amount': [1599, 1049, 1275, 899, 2050]
}

df = pd.DataFrame(restaurant_data)
print(df)
print(type(df))

print(df['waitername'])
print(type(df['waitername']))

   tableno waitername   order  amount
0        1       John   Pizza    1599
1        2      Alice  Burger    1049
2        3        Bob   Pasta    1275
3        4        Eve   Salad     899
4        5    Charlie   Sushi    2050
<class 'pandas.core.frame.DataFrame'>
0       John
1      Alice
2        Bob
3        Eve
4    Charlie
Name: waitername, dtype: object
<class 'pandas.core.series.Series'>

In [ ]:
total_bill = [470, 230, 405, 358]
s = pd.Series(total_bill, index=['mon', 'tue', 'wed', 'thu'])
print(s)
print(s.values)

mon    470
tue    230
wed    405
thu    358
dtype: int64
[470 230 405 358]

In [ ]:
df = pd.read_csv("tip.csv")

In [ ]:
df.head(3)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3

In [ ]:
print(df.tail(8))

     total_bill   tip     sex smoker   day    time  size
236       12.60  1.00    Male    Yes   Sat  Dinner     2
237       32.83  1.17    Male    Yes   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [ ]:
df.sample()

     total_bill  tip   sex smoker  day    time  size
112       38.07  4.0  Male     No  Sun  Dinner     3

In [ ]:
df.sample(6)

     total_bill   tip     sex smoker   day    time  size
210       30.06  2.00    Male    Yes   Sat  Dinner     3
76        17.92  3.08    Male    Yes   Sat  Dinner     2
19        20.65  3.35    Male     No   Sat  Dinner     3
80        19.44  3.00    Male    Yes  Thur   Lunch     2
95        40.17  4.73    Male    Yes   Fri  Dinner     4
52        34.81  5.20  Female     No   Sun  Dinner     4

In [ ]:
df.shape

(244, 7)

In [ ]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [ ]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [ ]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [ ]:
df['day'].unique()

array(['No', 'Yes'], dtype=object)

In [ ]:
df['day'].nunique()

4